import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif", "Plus Jakarta Sans"],
        heading: ["var(--font-inter)", "sans-serif", "Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "label-lg": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"],
        "headline-sm": ["Plus Jakarta Sans"],
        "body-md": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "display-mobile": ["Plus Jakarta Sans"],
        "title-md": ["Plus Jakarta Sans"],
        "title-lg": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "label-md": ["Plus Jakarta Sans"],
        "display": ["Plus Jakarta Sans"],
        "label-sm": ["Plus Jakarta Sans"]
      },
      colors: {
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          dark: "hsl(var(--primary-dark))",
        },
        accent: "hsl(var(--accent))",
        success: "hsl(var(--success))",
        "surface-tint":"#b12d0b",
        "surface":"#f9f9ff",
        "on-tertiary":"#ffffff",
        "on-secondary":"#ffffff",
        "on-error":"#ffffff",
        "secondary-fixed":"#6ffbbe",
        "on-secondary-fixed-variant":"#005236",
        "surface-container-highest":"#dce2f7",
        "outline":"#8e7069",
        "primary-fixed":"#ffdad2",
        "secondary-container":"#6cf8bb",
        "surface-bright":"#f9f9ff",
        "surface-container-high":"#e1e8fd",
        "on-secondary-fixed":"#002113",
        "inverse-surface":"#293040",
        "inverse-on-surface":"#edf0ff",
        "tertiary":"#4648d4",
        "surface-dim":"#d3daef",
        "secondary":"#006c49",
        "surface-container-low":"#f1f3ff",
        "on-primary":"#ffffff",
        "primary-fixed-dim":"#ffb4a2",
        "surface-container-lowest":"#ffffff",
        "tertiary-container":"#6063ee",
        "tertiary-fixed-dim":"#c0c1ff",
        "on-background":"#141b2b",
        "on-error-container":"#93000a",
        "outline-variant":"#e2bfb7",
        "error":"#ba1a1a",
        "on-tertiary-container":"#fffbff",
        "on-secondary-container":"#00714d",
        "secondary-fixed-dim":"#4edea3",
        "on-primary-fixed":"#3d0700",
        "tertiary-fixed":"#e1e0ff",
        "on-primary-container":"#fffbff",
        "surface-container":"#e9edff",
        "on-surface-variant":"#5a413b",
        "on-tertiary-fixed-variant":"#2f2ebe",
        "inverse-primary":"#ffb4a2",
        "primary-container":"#d04321",
        "on-tertiary-fixed":"#07006c",
        "on-surface":"#141b2b",
        "error-container":"#ffdad6",
        "surface-variant":"#dce2f7",
        "on-primary-fixed-variant":"#8a1c00"
      },
      spacing: {
        "space-xs":"0.25rem",
        "margin":"2rem",
        "margin-lg":"3rem",
        "space-md":"1rem",
        "gutter-lg":"2rem",
        "margin-sm":"1rem",
        "gutter-sm":"1rem",
        "gutter":"1.5rem",
        "space-xl":"2.5rem",
        "space-lg":"1.5rem",
        "space-sm":"0.5rem",
        "margin-desktop":"3rem",
        "margin-mobile":"1rem"
      },
      fontSize: {
        "headline-lg":["32px",{"lineHeight":"40px","letterSpacing":"-0.015em","fontWeight":"600"}],
        "headline-lg-mobile":["26px",{"lineHeight":"34px","letterSpacing":"-0.01em","fontWeight":"600"}],
        "label-lg":["14px",{"lineHeight":"20px","fontWeight":"500"}],
        "body-sm":["13px",{"lineHeight":"18px","fontWeight":"400"}],
        "headline-sm":["20px",{"lineHeight":"28px","letterSpacing":"-0.005em","fontWeight":"600"}],
        "body-md":["14px",{"lineHeight":"22px","fontWeight":"400"}],
        "headline-md":["24px",{"lineHeight":"32px","letterSpacing":"-0.01em","fontWeight":"600"}],
        "display-mobile":["32px",{"lineHeight":"40px","letterSpacing":"-0.025em","fontWeight":"800"}],
        "title-md":["16px",{"lineHeight":"24px","fontWeight":"600"}],
        "title-lg":["18px",{"lineHeight":"26px","fontWeight":"600"}],
        "body-lg":["16px",{"lineHeight":"26px","fontWeight":"400"}],
        "label-md":["12px",{"lineHeight":"16px","letterSpacing":"0.01em","fontWeight":"500"}],
        "display":["40px",{"lineHeight":"48px","letterSpacing":"-0.02em","fontWeight":"700"}],
        "label-sm":["11px",{"lineHeight":"14px","letterSpacing":"0.02em","fontWeight":"600"}]
      },
      keyframes: {
        marquee: {
          '0%': { transform: 'translateX(0%)' },
          '100%': { transform: 'translateX(-50%)' },
        }
      },
      animation: {
        marquee: 'marquee 20s linear infinite',
      },
    },
  },
  plugins: [],
};
export default config;
